### ISSUE TITLE
Quid Oldreader support?

### ISSUE THREAD

**Issue by dgoosens** [mrgodhani/rss-reader#1]
Hello

Wondering if you'd consider the Oldreader (or Feedly) support?

dGo

**Comment by mrgodhani** [comment]
@dgoosens that can be one of the enhancement. How would you want to integrate with feedly? In the sense of synchronize it in app for later offline read etc?

**Comment by dgoosens** [comment]
I find both are terrible for Desktop users (work nicely on mobile devices) and figure it would be nice to be able to check out the feeds that are stored in those apps within your application.

Basically, one would only need to sign in and your rss-reader would sync new/read feeds automatically every n minutes.

I guess these apps have some sort of API that would enable you to do so?

**Comment by mrgodhani** [comment]
I guess feedly has API have to look into other one.

**Comment by dgoosens** [comment]
found this:  
<https://github.com/theoldreader/api>
