### ISSUE TITLE
Logo / Branding

### ISSUE THREAD

**Issue by thenexxuz** [mrgodhani/rss-reader#11]
Do you have any ideas for a logo / branding for RSS Reader? I have not seen anything for it (I don't think).

If not would you be open to some ideas?

**Comment by mrgodhani** [comment]
@thenexxuz  Yes actually I am open to some ideas do you have one ?

**Comment by thenexxuz** [comment]
I was wanting to first bounce some ideas off of a graphic designer friend of mine first... (he has a real eye for these types of things).

**Comment by thenexxuz** [comment]
![rss-reader](https://cloud.githubusercontent.com/assets/1750061/17027849/3ebaabb2-4f2b-11e6-8a84-a36f4bb3817a.png)
This is one of the designs that he came up with... any thoughts?

**Comment by mrgodhani** [comment]
Is that for the icon ?

**Comment by thenexxuz** [comment]
Yes.  There was another one he also created with a man on profile wearing a monocle and top hat  with a big bushy mustache and the RSS logo as the eye.

**Comment by mrgodhani** [comment]
Can I see that too ?

**Comment by thenexxuz** [comment]
Imagine this https://lh3.googleusercontent.com/-OGu0q1Lrx90/VUxZ_gF67kI/AAAAAAAAATk/kFAWanwfnpw/w1024-h1024/37607e_02b3c0278a6e462babe520b1da3d724f.png
with the RSS logo in the eye.

**Comment by thenexxuz** [comment]
I didn't have time to create that one.

**Comment by mrgodhani** [comment]
I will consider looking at more options if someone else have it too. Or I am even open to put out a small competition out there and pay amount prize to whoever comes out with good design logo.
