### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by thenexxuz** [mrgodhani/rss-reader#12]
I just noticed that the builds that I made yesterday did not have icons. (See screenshot of OSX version) this is also for the Linux version (I assume the windows version too).

![screen shot 2016-07-16 at 3 25 12 pm](https://cloud.githubusercontent.com/assets/1750061/16896996/c5584e38-4b69-11e6-8ca3-45fb9738922b.png)

**Comment by mrgodhani** [comment]
Hm I will investigate and fix it.

**Comment by thenexxuz** [comment]
I think that I missed a dependency when installing... but I do not remember which.

**Comment by crwgregory** [comment]
I also have this issue, windows 10. Also, probably unrealted but I had to manually install `minimist` to `npm run release`.

![image](https://cloud.githubusercontent.com/assets/9405969/17000587/69b6446c-4e80-11e6-9e5e-18b6958521b2.png)

**Comment by mrgodhani** [comment]
Yep figuring out somehow one of the reasons why that is happening is because fontawesome is not getting loaded.

**Comment by mrgodhani** [comment]
Please repackage it. Should be fixed now.
