### ISSUE TITLE
javascript error in the main process

### ISSUE THREAD

**Issue by codenoid** [mrgodhani/rss-reader#16]
hi, i'm trying to install your rss-reader, but, i found some error,
my python , 2.7 and 3.6, node v 6.10, package, etc , lates version.
http://s10.postimg.org/4l9cywmix/my_first_ruby.jpg 
my screenshot, thanks. :+1:

**Comment by mrgodhani** [comment]
@codenoid Did you try changing your node version to latest and rebuild it?

**Comment by codenoid** [comment]
i'll try it
