### ISSUE TITLE
npm run build error on mac and linux(happened on my friend's arch linux)

### ISSUE THREAD

**Issue by silemelon** [mrgodhani/rss-reader#17]
Using 'npm install electron --save-dev' install Atom/Electron first then 'npm install',everything is ok,but 'npm run release' error, info is:
ERROR in ./app/~/got/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./package in /Users/XX/WorkSpace/Js/rss-reader/app/node_modules/got
 @ ./app/~/got/index.js 19:12-32

ERROR in app.js from UglifyJs
SyntaxError: Unexpected token: name (redirectCount) [./app/~/got/index.js:26,0]

**Comment by mrgodhani** [comment]
@silemelon What npm and node version are you using?

**Comment by silemelon** [comment]
@mrgodhani  npm 3.10.9,node v7.2.1

**Comment by mrgodhani** [comment]
@silemelon  Should work. I will look into it. p.s Vue 2.0 is on it's way as well.

**Comment by silemelon** [comment]
@mrgodhani Hi,how about your try,I'm looking for your response.It doesn't work on my pc.

**Comment by weaming** [comment]
same, build error.

could you release the built installers?
