### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [mrgodhani/rss-reader#19]
First, thanks for building this!

Second, what license should is this code under? Currently, I can't find one stated anywhere--which means it's "All Rights Reserved" in most jurisdictions.

I noticed your [bookmark](https://github.com/mrgodhani/bookmark) project is under the MIT. Perhaps that was the intent here also?

It'd be helpful to clarify the license for encouraging outside contribution and further use.

Thanks!
🎩

**Comment by mrgodhani** [comment]
Yes it should be MIT license. I will update in master branch. But in newer version of code https://github.com/mrgodhani/rss-reader/tree/newversion it would be MIT

**Comment by mrgodhani** [comment]
Added

**Comment by BigBlueHat** [comment]
Thanks for the fast work on this!
