### ISSUE TITLE
Can´t highlight text (and therefore I cant copy text from the reader).

### ISSUE THREAD

**Issue by sujumayas** [mrgodhani/rss-reader#21]
Maybe this is just a #todo more than a bug, but I think the reader cannot work without the ability to highlight and copy text. 

E.

**Comment by mrgodhani** [comment]
@sujumayas I would still tag it as a bug. No drag/select was on body by mistake. Will be removing that and releasing it soon later today.

**Comment by mrgodhani** [comment]
Fixed in https://github.com/mrgodhani/rss-reader/releases/tag/v0.1.12
