### ISSUE TITLE
Any recommendation or suggestion of implementing cron job type worker?

### ISSUE THREAD

**Issue by mrgodhani** [mrgodhani/rss-reader#29]
I am trying to work on better solution of handling updating of feeds regularly. Does anyone has solution of implementing cronjob like background process to refresh feeds and add latest articles in electron ?

So far only I can think of either using background process by booting up invisible browser or figure out way of using web workers.  I also do now want to block UI. And trying to make it smooth and optimal.

**Comment by sujumayas** [comment]
You could maybe use this: https://github.com/node-schedule/node-schedule

I read the docs and it can work for you. Was searching if it will have problems with electron and I only found this: 

https://github.com/node-schedule/node-schedule/issues/319

So I think it works fine. 

Good luck! 
😄

**Comment by mrgodhani** [comment]
@sujumayas Awesome thanks
