### ISSUE TITLE
Need windows installer fixed from upstream package

### ISSUE THREAD

**Issue by srhise** [mrgodhani/rss-reader#3]
I couldn't get this to work on Windows until I pulled in this commit 

https://github.com/mikerockett/electron-boilerplate-vue/commit/cb6ad525ee742099663367f4d5085d01a332dcee

**Comment by mrgodhani** [comment]
@srhise thanks for letting me know I will look into this. If you want you could also make a PR.

**Comment by mrgodhani** [comment]
Issue is fixed.

**Comment by srhise** [comment]
Thanks!
