### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Vastrix** [mrgodhani/rss-reader#72]
|  
-----|-----
OS | Windows 10
Version | 0.1.15

### Very Minor _issue_
- `About Application` doesn't work
- `Export Subscription` doesn't work

### Suggestions
- When adding new feeds, have the little checkmark be checked by default
- When offline reading becomes a thing, allow to specify how long the cached data should be kept
- Allow to specify the refresh interval (when to check for new news)
- Minimize to tray
- Notification upon new news
- Dark Mode
- Mark all as read

All in all, a very slick interface and ofcourse a functional program, great job! :)

**Comment by mrgodhani** [comment]
@Vastrix great feedback. I will look into this

**Comment by Vastrix** [comment]
@mrgodhani I guess it would be cool if you could do it per feed :o 
In case you have a feed you'd like to keep a closer eye on..

**Comment by mrgodhani** [comment]
@Vastrix Export subscription does work. Only problem is that it doesn't notify as it does on mac. I will resolve that.

**Comment by mrgodhani** [comment]
https://github.com/mrgodhani/rss-reader/releases/tag/v0.2.2

- [ ] - When adding new feeds, have the little checkmark be checked by default
- [ ] - When offline reading becomes a thing, allow to specify how long the cached data should be kept
- [x] - Allow to specify the refresh interval (when to check for new news)
- [x] - Minimize to tray
- [x] - Notification upon new news
- [x] - Dark Mode
- [ ] - Mark all as read

**Comment by mrgodhani** [comment]
Closing this above would be included in latest release except offline

**Comment by Vastrix** [comment]
Hey, I updated but can't find the option to `mark all as read`? :o

**Comment by mrgodhani** [comment]
@Vastrix I still have to release mark all as read. I will do it today

**Comment by Vastrix** [comment]
oh waw, yea indeed, my bad :s
