### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by ramstein74** [mrgodhani/rss-reader#8]
hi , i tried this app but i get a blank page. 
thank you
![image](https://cloud.githubusercontent.com/assets/1210858/14673370/87ec7f46-06f5-11e6-9840-7b035f7fd6de.png)

Is there any db setup i need to do?

**Comment by mrgodhani** [comment]
Ah, Windows. There is no DB setup needed. I use NeDB which is basically a document based database. I will get back to you on this. Although should work.
