### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MrSassyBritches** [mrgodhani/rss-reader#9]
I dont understand how to install this. Im on windows 10.

**Comment by mrgodhani** [comment]
@MrSassyBritches as per instruction you need to install Atom Electron on your pc as well as NPM. Once you have done that follow the instructions from readme.

By going to cloned directory and executing below commands

npm install   // install dependencies

npm run release   // package app, will create app in release directory.

Build for windows should be there on release directory. I myself use mac only so didn't get chance to test it out on Windows machine.

**Comment by BigBlueHat** [comment]
On Windows 10 I'm mostly seeing webpack errors:
```
WARNING in ./app/~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./app/~/encoding/lib/iconv-loader.js 9:12-34

ERROR in ./app/app.js
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app
 @ ./app/app.js 42:10-27

ERROR in ./app/~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./app/~/vue-loader/lib/selector.js?type=script&index=0!./app/components/Main.vue
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app\components
 @ ./app/~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./app/~/vue-loader/lib/selector.js?type=script&index=0!./app/components/Main.vue 26:10-27

ERROR in ./app/~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./app/~/vue-loader/lib/selector.js?type=script&index=0!./app/components/ManageFeed.vue
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app\components
 @ ./app/~/babel-loader?optional[]=runtime&loose=all&nonStandard=false!./app/~/vue-loader/lib/selector.js?type=script&index=0!./app/components/ManageFeed.vue 11:10-27 15:13-30

ERROR in ./app/helpers/refresh.js
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app\helpers
 @ ./app/helpers/refresh.js 37:10-27

ERROR in ./app/helpers/queue.js
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app\helpers
 @ ./app/helpers/queue.js 21:10-27

ERROR in ./app/db.js
Module not found: Error: Cannot resolve module 'remote' in c:\Users\Benjamin\Documents\GitHub\rss-reader\app
 @ ./app/db.js 4:10-27
```

I'm new to webpack (preferring browserify), but I'd love to give this reader a try (as I do a good bit of Vue.js coding).

Any thoughts on those errors?

**Comment by BigBlueHat** [comment]
I also got this one about `NSIS` after those earlier ones:
```
[10:04:29] Building installer with NSIS...

c:\Users\Benjamin\Documents\GitHub\rss-reader\tasks\release_windows.js:100
            throw "Can't find NSIS. Are you sure you've installed it and"
            ^
 Can't find NSIS. Are you sure you've installed it and added to PATH environment variable?
```

**Comment by mrgodhani** [comment]
@BigBlueHat For remote module resolve, I will push the fix for it. It's mainly changing part of require code to `require('electron').remote`. Regarding NSIS did you configured it properly under Environment Variable ? or installed NSIS from http://nsis.sourceforge.net/Main_Page ?

**Comment by thenexxuz** [comment]
I am having the same issue on Fedora. I would be happy to help update the API...but where should begin?

**Comment by mrgodhani** [comment]
@thenexxuz So you are not able to package for Fedora ? Issue might be inside packaging. Packaging is handled by https://github.com/electron-userland/electron-packager. And since Fedora is Linux it relies on https://github.com/mrgodhani/rss-reader/blob/master/tasks/release_linux.js.  I am working on updated version already with new version of vuex and latest version of electron. Which I intened to release it by this sunday. If you can figure out how to fix the API that would be the place. And you can always post PR.

**Comment by mrgodhani** [comment]
@thenexxuz  I just pushed new release. Still needs some updates as I am adding features into it. But you can not try packaging your app and should work.

**Comment by thenexxuz** [comment]
@mrgodhani yes it compiles now! Thank you!
